name: CI test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Find pull request
      #   uses: juliangruber/find-pull-request-action@v1
      #   id: find-pull-request
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
      #     base: master
          
      - name: Request review
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "9",
              reviewers: [context.actor]
            })
